channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
      - pypdf==3.12.0
      - requests==2.31.0
      - robocorp-http==0.2.0
      - robocorp-storage==0.2.0
      - robocorp-tasks==2.0.0
      - robocorp-vault==0.4.0
      - robocorp-workitems==1.2.1
